#!/bin/bash
Rscript var_ols.R --path=tempdata_tf/author_cluster_0_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_0_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_1_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_1_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_2_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_2_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_5_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_5_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_6_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_6_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_8_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_8_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_9_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_9_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_10_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_10_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_11_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_11_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_12_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_12_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_13_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_13_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_14_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_14_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_15_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_15_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_17_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_17_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_18_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_18_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_19_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_19_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_21_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_21_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_22_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_22_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_23_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_23_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_24_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_24_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_25_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_25_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_26_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_26_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_27_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_27_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_28_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_28_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_29_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_29_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_30_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_30_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_31_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_31_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_37_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_37_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_38_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_38_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_39_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_39_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_40_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_40_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_41_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_41_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_43_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_43_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_44_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_44_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_45_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_45_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_46_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_46_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_47_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_47_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_48_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_48_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_49_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_49_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_50_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_50_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_51_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_51_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_52_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_52_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_53_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_53_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_54_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_54_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_55_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_55_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_56_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_56_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_57_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_57_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_58_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_58_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_59_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_59_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_60_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_60_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_61_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_61_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_62_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_62_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_63_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_63_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_64_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_64_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_65_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_65_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_66_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_66_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_67_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_67_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_68_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_68_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_69_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_69_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_70_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_70_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_71_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_71_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_72_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_72_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_73_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_73_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_74_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_74_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_75_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_75_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_76_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_76_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_77_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_77_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_78_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_78_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_79_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_79_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_80_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_80_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_81_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_81_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_82_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_82_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_84_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_84_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_85_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_85_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_86_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_86_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_87_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_87_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_88_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_88_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_90_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_90_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_91_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_91_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_92_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_92_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_93_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_93_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_94_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_94_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_95_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_95_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_96_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_96_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_98_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_98_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_99_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_99_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_100_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_100_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_101_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_101_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_102_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_102_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_103_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_103_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_105_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_105_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_106_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_106_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_107_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_107_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_108_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_108_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_109_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_109_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_110_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_110_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_111_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_111_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_112_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_112_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_114_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_114_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_115_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_115_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_116_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_116_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_117_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_117_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_118_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_118_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_119_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_119_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_120_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_120_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_121_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_121_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_123_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_123_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_125_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_125_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_126_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_126_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_127_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_127_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_129_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_129_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_130_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_130_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_131_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_131_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_132_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_132_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_133_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_133_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_134_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_134_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_135_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_135_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_137_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_137_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_138_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_138_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_139_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_139_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_140_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_140_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_141_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_141_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_142_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_142_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_143_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_143_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_144_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_144_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_146_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_146_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_147_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_147_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_148_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_148_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_149_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_149_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_151_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_151_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_153_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_153_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_154_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_154_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_155_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_155_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_156_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_156_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_157_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_157_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_158_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_158_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_159_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_159_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_160_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_160_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_161_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_161_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_162_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_162_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_163_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_163_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_164_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_164_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_165_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_165_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_166_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_166_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_167_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_167_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_168_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_168_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_169_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_169_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_170_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_170_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_171_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_171_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_172_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_172_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_173_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_173_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_174_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_174_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_176_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_176_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_177_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_177_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_178_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_178_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_179_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_179_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_180_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_180_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_181_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_181_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_182_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_182_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_183_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_183_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_184_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_184_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_185_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_185_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_188_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_188_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_189_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_189_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_190_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_190_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_191_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_191_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_192_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_192_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_193_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_193_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_195_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_195_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_196_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_196_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_197_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_197_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_198_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_198_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_199_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_199_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_200_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_200_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_201_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_201_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_202_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_202_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_204_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_204_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_205_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_205_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_206_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_206_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_207_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_207_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_208_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_208_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_210_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_210_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_212_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_212_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_213_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_213_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_214_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_214_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_217_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_217_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_218_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_218_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_219_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_219_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_220_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_220_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_221_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_221_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_222_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_222_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_223_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_223_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_224_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_224_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_225_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_225_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_226_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_226_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_227_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_227_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_228_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_228_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_229_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_229_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_230_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_230_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_231_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_231_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_232_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_232_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_233_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_233_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_236_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_236_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_237_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_237_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_238_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_238_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_239_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_239_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_240_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_240_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_241_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_241_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_242_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_242_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_243_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_243_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_244_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_244_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_245_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_245_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_246_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_246_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_247_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_247_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_248_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_248_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_249_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_249_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_250_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_250_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_251_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_251_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_252_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_252_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_253_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_253_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_255_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_255_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_256_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_256_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_257_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_257_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_258_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_258_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_259_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_259_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_260_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_260_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_262_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_262_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_263_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_263_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_265_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_265_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_266_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_266_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_267_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_267_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_268_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_268_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_269_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_269_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_271_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_271_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_273_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_273_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_274_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_274_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_275_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_275_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_276_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_276_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_277_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_277_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_278_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_278_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_279_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_279_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_280_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_280_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_281_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_281_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_282_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_282_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_283_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_283_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_285_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_285_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_286_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_286_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_287_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_287_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_288_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_288_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_289_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_289_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_290_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_290_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_291_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_291_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_292_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_292_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_293_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_293_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_294_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_294_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_295_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_295_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_296_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_296_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_297_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_297_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_298_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_298_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_299_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_299_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_300_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_300_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_301_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_301_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_303_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_303_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_304_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_304_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_305_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_305_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_306_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_306_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_307_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_307_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_308_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_308_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_309_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_309_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_310_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_310_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_311_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_311_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_312_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_312_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_313_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_313_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_314_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_314_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_315_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_315_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_316_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_316_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_317_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_317_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_318_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_318_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_319_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_319_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_320_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_320_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_321_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_321_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_322_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_322_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_323_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_323_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_324_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_324_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_325_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_325_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_326_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_326_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_327_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_327_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_328_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_328_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_329_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_329_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_330_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_330_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_331_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_331_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_332_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_332_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_333_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_333_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_334_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_334_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_335_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_335_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_336_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_336_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_337_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_337_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_338_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_338_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_339_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_339_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_340_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_340_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_342_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_342_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_343_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_343_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_344_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_344_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_345_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_345_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_346_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_346_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_348_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_348_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_350_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_350_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_351_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_351_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_352_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_352_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_354_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_354_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_355_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_355_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_356_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_356_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_357_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_357_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_358_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_358_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_359_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_359_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_360_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_360_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_361_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_361_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_362_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_362_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_363_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_363_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_364_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_364_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_365_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_365_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_366_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_366_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_367_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_367_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_368_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_368_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_369_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_369_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_370_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_370_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_371_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_371_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_372_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_372_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_373_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_373_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_374_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_374_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_375_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_375_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_376_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_376_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_377_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_377_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_378_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_378_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_379_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_379_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_380_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_380_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_381_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_381_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_382_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_382_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_384_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_384_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_385_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_385_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_386_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_386_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_387_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_387_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_388_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_388_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_389_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_389_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_390_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_390_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_392_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_392_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_393_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_393_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_394_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_394_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_395_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_395_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_396_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_396_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_397_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_397_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_398_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_398_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_399_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_399_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_400_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_400_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_401_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_401_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_402_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_402_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_403_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_403_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_404_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_404_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_405_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_405_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_406_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_406_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_407_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_407_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_408_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_408_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_409_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_409_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_410_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_410_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_411_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_411_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_413_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_413_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_414_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_414_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_415_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_415_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_417_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_417_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_418_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_418_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_419_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_419_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_420_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_420_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_421_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_421_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_422_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_422_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_423_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_423_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_424_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_424_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_425_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_425_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_426_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_426_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_427_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_427_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_428_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_428_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_429_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_429_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_432_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_432_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_433_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_433_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_434_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_434_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_436_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_436_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_437_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_437_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_438_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_438_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_439_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_439_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_440_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_440_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_441_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_441_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_442_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_442_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_443_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_443_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_444_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_444_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_445_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_445_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_446_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_446_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_447_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_447_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_448_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_448_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_449_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_449_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_450_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_450_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_451_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_451_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_452_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_452_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_453_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_453_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_454_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_454_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_455_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_455_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_456_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_456_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_457_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_457_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_459_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_459_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_460_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_460_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_461_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_461_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_462_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_462_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_463_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_463_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_464_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_464_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_466_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_466_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_467_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_467_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_468_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_468_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_469_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_469_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_470_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_470_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_471_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_471_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_472_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_472_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_473_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_473_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_475_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_475_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_476_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_476_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_477_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_477_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_478_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_478_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_480_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_480_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_481_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_481_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_483_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_483_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_484_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_484_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_485_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_485_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_486_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_486_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_487_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_487_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_488_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_488_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_489_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_489_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_490_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_490_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_491_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_491_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_492_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_492_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_493_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_493_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_494_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_494_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_495_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_495_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_496_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_496_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_497_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_497_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_498_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_498_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_499_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_499_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_500_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_500_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_501_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_501_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_502_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_502_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_503_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_503_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_504_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_504_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_505_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_505_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_506_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_506_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_507_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_507_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_508_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_508_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_509_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_509_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_510_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_510_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_511_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_511_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_512_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_512_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_513_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_513_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_514_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_514_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_516_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_516_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_517_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_517_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_518_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_518_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_519_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_519_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_520_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_520_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_521_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_521_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_522_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_522_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_523_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_523_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_524_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_524_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_525_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_525_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_526_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_526_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_527_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_527_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_529_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_529_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_530_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_530_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_531_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_531_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_532_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_532_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_533_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_533_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_534_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_534_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_535_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_535_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_536_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_536_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_537_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_537_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_538_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_538_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_539_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_539_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_540_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_540_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_541_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_541_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_542_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_542_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_543_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_543_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_544_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_544_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_545_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_545_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_546_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_546_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_547_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_547_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_548_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_548_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_549_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_549_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_550_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_550_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_551_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_551_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_552_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_552_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_553_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_553_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_554_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_554_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_555_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_555_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_556_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_556_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_557_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_557_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_558_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_558_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_559_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_559_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_561_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_561_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_562_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_562_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_563_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_563_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_564_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_564_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_565_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_565_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_567_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_567_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_568_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_568_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_569_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_569_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_570_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_570_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_571_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_571_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_572_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_572_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_573_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_573_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_574_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_574_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_575_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_575_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_577_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_577_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_578_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_578_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_579_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_579_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_580_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_580_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_581_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_581_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_582_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_582_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_583_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_583_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_585_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_585_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_586_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_586_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_587_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_587_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_588_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_588_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_589_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_589_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_590_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_590_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_591_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_591_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_592_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_592_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_593_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_593_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_594_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_594_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_595_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_595_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_596_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_596_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_597_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_597_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_599_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_599_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_600_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_600_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_601_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_601_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_602_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_602_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_603_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_603_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_604_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_604_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_605_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_605_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_606_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_606_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_607_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_607_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_609_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_609_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_610_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_610_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_611_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_611_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_612_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_612_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_613_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_613_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_614_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_614_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_615_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_615_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_618_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_618_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_619_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_619_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_620_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_620_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_621_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_621_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_622_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_622_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_623_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_623_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_624_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_624_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_625_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_625_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_626_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_626_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_627_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_627_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_628_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_628_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_629_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_629_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_630_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_630_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_631_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_631_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_632_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_632_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_633_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_633_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_634_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_634_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_635_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_635_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_636_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_636_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_637_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_637_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_638_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_638_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_639_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_639_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_640_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_640_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_641_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_641_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_642_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_642_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_643_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_643_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_644_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_644_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_645_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_645_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_647_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_647_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_648_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_648_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_649_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_649_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_650_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_650_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_651_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_651_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_652_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_652_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_653_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_653_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_655_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_655_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_656_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_656_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_657_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_657_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_658_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_658_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_659_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_659_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_660_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_660_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_661_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_661_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_663_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_663_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_664_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_664_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_665_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_665_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_666_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_666_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_667_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_667_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_669_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_669_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_670_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_670_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_671_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_671_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_672_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_672_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_674_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_674_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_676_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_676_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_677_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_677_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_678_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_678_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_679_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_679_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_680_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_680_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_681_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_681_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_682_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_682_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_683_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_683_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_684_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_684_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_685_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_685_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_687_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_687_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_688_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_688_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_689_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_689_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_690_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_690_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_691_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_691_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_692_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_692_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_693_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_693_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_696_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_696_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_698_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_698_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_699_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_699_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_700_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_700_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_701_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_701_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_704_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_704_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_706_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_706_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_707_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_707_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_708_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_708_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_709_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_709_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_710_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_710_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_713_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_713_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_714_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_714_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_716_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_716_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_718_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_718_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_722_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_722_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_723_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_723_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_724_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_724_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_725_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_725_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_727_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_727_tf
Rscript var_ols.R --path=tempdata_tf/author_cluster_729_tf.feather --forecast-length=24 --runs=200 --name=author_cluster_729_tf
