* Notes on fitting SMAP
** Cross validation
   The main task in model fitting is to choose hyperparameters through cross validation.
   The set of hyperparameters includes:
   1. kernel function (that maps weights to distances on the manifold. Exponential is often a default)
   2. Elasticnet regularization parameter (ratio of L1 to L2 norm)
   3. Kernel bandwidth (controls amount of nonlinearity)
   4. lambda (controls amount of regularization)
   5. number of lags.

   Cenci recommends selection in two steps. First choose 1. and 2. and then choose 3-5. 

   I care about finding out if I need SMAP (or if dynamical var models can work instead).  So I will do an exercise on a single cluster. I'll disable regularization and choose the exponential kernel function and then grid sweep just No. lags and kernel bandwidth and see if theta > 0 helps. 

   Next I'll run that version on all the clusters to check the typical values of theta (are they greater than 0?).

   For simplicity I think I'll choose the same kernel function for all. I should test that the exponential kernal is a good choice but if it isn't the best that would be good to know.

   If we detect nonlinearity (theta > 0) then I'll run the full analysis without regularization and then with regularization. Adding regularization will improve forecasting performance but will take more computer time. 
   
** Cenci's code
   It seems pretty good, though Italian.
   I'll build a more scriptable API over top of it and then run it. 
   
